import catalog from './catalog.json';
import {readingStatus} from './reader-model.js';
export function initialize(){
'use strict';
const books = catalog;
window.margenBooks=books;
const $ = s => document.querySelector(s);
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readStore(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let shelf = readStore('margen-shelf',{}); if(!shelf || typeof shelf!=='object' || Array.isArray(shelf)) shelf={};
let notes = readStore('margen-notes',[]); if(!Array.isArray(notes)) notes=[];
let category='Todos', mood=null, detailId=null, toastTimer;
function persist(){try{localStorage.setItem('margen-shelf',JSON.stringify(shelf));localStorage.setItem('margen-notes',JSON.stringify(notes));return true}catch{toast('No se pudo guardar en este navegador. Exporta tu biblioteca.');return false}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function palette(b){return `--stage:${b.colors[0]};--cover:${b.colors[1]};--text:${b.colors[2]};--art:${b.colors[3]}`}
function cover(b){return `<div class="cover design-${b.id%5}" aria-hidden="true"><span class="author">${b.author}</span><strong class="title">${b.title}</strong><div class="cover-art"></div><span class="publisher">MARGEN / ${String(b.id).padStart(2,'0')}</span></div>`}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function render(){let q=normalize($('#search').value.trim());let list=books.filter(b=>(category==='Todos'||b.category===category)&&(!mood||b.mood===mood)&&normalize(`${b.title} ${b.author} ${b.tag} ${b.description}`).includes(q));if(window.margenSort==='title')list.sort((a,b)=>a.title.localeCompare(b.title,'es'));if(window.margenSort==='pages')list.sort((a,b)=>a.pages-b.pages);$('#book-grid').innerHTML=list.map(b=>`<article class="book-card" style="${palette(b)}"><div class="book-stage"><button class="book-open" data-open="${b.id}" aria-label="Ver ${b.title}">${cover(b)}</button><button class="save ${shelf[b.id]?'saved':''}" data-save="${b.id}" aria-label="${shelf[b.id]?'Quitar':'Guardar'} ${b.title}" aria-pressed="${!!shelf[b.id]}">${shelf[b.id]?'♥':'♡'}</button></div><p class="book-category">${b.category} / ${b.tag}</p><h3><button data-open="${b.id}" style="padding:0;text-align:left;font:inherit">${b.title}</button></h3><p class="book-author">${b.author}</p><div class="book-meta"><span>Leer en flipbook ↗</span><span>${b.pages} páginas</span></div></article>`).join('');$('#results-count').textContent=`${list.length} ${list.length===1?'historia':'historias'} por descubrir${mood?' · '+({calma:'Una pausa',viaje:'Ir lejos',ideas:'Otra perspectiva'}[mood]):''}`;$('#empty').hidden=!!list.length;$('#shelf-count').textContent=books.filter(b=>shelf[b.id]).length;}
function toggleSave(id){if(shelf[id]){delete shelf[id];toast('Libro retirado de tu biblioteca')}else{shelf[id]='Por leer';toast('Una nueva historia en tu biblioteca')}persist();render();renderShelf();if(detailId===id)renderDetail(id)}
function renderDetail(id){const b=books.find(b=>b.id===id);detailId=id;$('#book-detail').innerHTML=`<div class="detail-layout"><div class="detail-cover" style="${palette(b)}">${cover(b)}</div><div class="detail-copy"><p class="eyebrow">${b.category} · SELECCIÓN MARGEN</p><h2>${b.title}</h2><p>${b.author}</p><p>${b.description}</p><div class="detail-facts"><span>${b.language}</span><span>Publicado en ${b.year}</span></div><button class="button dark" data-read="${id}">Abrir libro ↗</button><p class="edition-source"><a href="https://www.gutenberg.org/ebooks/${id}" target="_blank" rel="noopener">Edición y créditos ↗</a></p><button class="text-button" data-save="${id}">${shelf[id]?'Retirar de mi biblioteca':'Guardar en mi biblioteca'} <span>${shelf[id]?'♥':'♡'}</span></button></div></div><div class="note"><p class="eyebrow">UNA PREGUNTA PARA LLEVARTE</p><p>${b.prompt}</p><button class="text-button" data-note="${id}">Escribir en mi bitácora ↗</button></div>`}
function showBook(id){renderDetail(id);$('#book-dialog').showModal()}
function renderShelf(){const list=books.filter(b=>shelf[b.id]);$('#shelf-content').innerHTML=list.length?list.map(b=>{const position=readStore('margen-position-'+b.id,null),status=readingStatus(position);return `<div class="shelf-row"><div><h3><button data-open-shelf="${b.id}" style="font:inherit;padding:0">${b.title}</button></h3><p>${b.author}</p><p class="shelf-progress">${position?`Página ${position.page+1} de ${b.pages} · ${status.percent}% recorrido`:"Tu historia está por comenzar"}</p></div><button class="shelf-resume" data-read="${b.id}">${position?.page>0?"Reanudar lectura":"Comenzar lectura"} ↗</button><span class="status-pill status-${status.key}" aria-label="Estado de lectura: ${status.label}">${status.label}</span><button data-remove="${b.id}" aria-label="Retirar ${b.title}">Retirar ×</button></div>`}).join(''):'<p class="empty">Tu biblioteca empieza con una historia.<br>Guarda un libro con el corazón ♡.</p>';$('#export').hidden=!list.length}
function renderNotes(){$('#notes').innerHTML=notes.map(n=>`<article class="note"><button data-delete-note="${escapeHTML(n.id)}" aria-label="Eliminar nota">Eliminar ×</button><h3>${escapeHTML(n.book)}</h3><p>${escapeHTML(n.text)}</p><small>${escapeHTML(n.date)}${n.page!=null?` · Página ${n.page+1}`:""}</small></article>`).join('')}
function openJournal(){renderNotes();$('#journal-dialog').showModal()}
document.addEventListener('click',e=>{let t=e.target.closest('button');if(!t)return;if(t.dataset.read){t.closest('dialog')?.close();window.dispatchEvent(new CustomEvent('margen-read',{detail:Number(t.dataset.read)}))}if(t.dataset.open)showBook(Number(t.dataset.open));if(t.dataset.save)toggleSave(Number(t.dataset.save));if(t.dataset.filter){category=t.dataset.filter;mood=null;document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('selected',el===t));render()}if(t.dataset.mood){mood=t.dataset.mood;category='Todos';$('#search').value='';document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('selected',el.dataset.filter==='Todos'));render();$('#catalogo').scrollIntoView({behavior:'smooth'})}if(t.dataset.remove)toggleSave(Number(t.dataset.remove));if(t.dataset.openShelf){$('#shelf-dialog').close();showBook(Number(t.dataset.openShelf))}if(t.dataset.note){const b=books.find(b=>b.id===Number(t.dataset.note));$('#book-dialog').close();$('#note-book').value=b.title;openJournal();$('#note-text').focus()}if(t.dataset.deleteNote){notes=notes.filter(n=>n.id!==t.dataset.deleteNote);persist();renderNotes();toast('Nota eliminada')}if(t.classList.contains('close'))t.closest('dialog').close()});
$('#search').addEventListener('input',render);window.addEventListener('margen-sort',render);$('#shelf-link').addEventListener('click',()=>{renderShelf();$('#shelf-dialog').showModal()});$('#journal-link').addEventListener('click',openJournal);$('#journal-cta').addEventListener('click',openJournal);$('#random-book').addEventListener('click',()=>showBook(books[Math.floor(Math.random()*books.length)].id));$('#note-form').addEventListener('submit',e=>{e.preventDefault();const book=$('#note-book').value.trim(),text=$('#note-text').value.trim();if(!book||!text)return;const origin=$('#journal-dialog').dataset.reader==='true';notes.unshift({id:crypto.randomUUID(),book,text,...(origin?{bookId:Number($('#journal-dialog').dataset.bookId),page:Number($('#journal-dialog').dataset.page)}:{}),date:new Date().toLocaleDateString('es-CO',{year:'numeric',month:'long',day:'numeric'})});persist();e.target.reset();renderNotes();if(origin){try{localStorage.removeItem('margen-note-draft-'+$('#journal-dialog').dataset.bookId)}catch{}$('#journal-dialog').close();delete $('#journal-dialog').dataset.reader;}toast('Tu descubrimiento se queda contigo')});$('#export').addEventListener('click',async()=>{const button=$('#export');button.disabled=true;button.textContent='Preparando PDF…';try{const {exportLibrary}=await import('./library-pdf.js');exportLibrary(books.filter(b=>shelf[b.id]).map(b=>({...b,position:readStore('margen-position-'+b.id,null)})));toast('Tu biblioteca en PDF está lista')}catch(error){console.error(error);toast('No pudimos preparar el PDF. Vuelve a intentarlo.')}finally{button.disabled=false;button.textContent='Descargar mi biblioteca PDF ↓'}});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('#search').focus();$('#catalogo').scrollIntoView()}});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));$('#year').textContent=new Date().getFullYear();render();

window.addEventListener('margen-reader-note',e=>{$('#note-book').value=e.detail.title;$('#note-text').value=e.detail.text||readStore('margen-note-draft-'+e.detail.id,{}).text||'';Object.assign($('#journal-dialog').dataset,{reader:'true',bookId:String(e.detail.id),page:String(e.detail.page)});openJournal();$('#note-text').focus()});
window.addEventListener('margen-read',e=>{const id=typeof e.detail==='object'?e.detail.id:e.detail;if(!shelf[id]){shelf[id]=true;persist();render();renderShelf()}});
window.addEventListener('margen-progress',renderShelf);
$('#note-form').addEventListener('input',()=>{const d=$('#journal-dialog').dataset;if(d.reader==='true'){try{const key='margen-note-draft-'+d.bookId;if($('#note-text').value)localStorage.setItem(key,JSON.stringify({text:$('#note-text').value}));else localStorage.removeItem(key);}catch{}}});
$('#journal-dialog').addEventListener('close',()=>{delete $('#journal-dialog').dataset.reader});
}


