import React from 'react';
export default function Shell(){return <>
<a className="skip" href="#catalogo">Ir al catálogo</a>
<header className="header"><a className="brand" href="#" aria-label="Margen, inicio"><span className="brand-symbol">m<span>↗</span></span>margen<span className="brand-dot">.</span></a><nav aria-label="Principal"><a className="active" href="#catalogo">Explorar</a><a href="#colecciones">Colecciones</a><button id="shelf-link">Mi biblioteca <span id="shelf-count">0</span></button></nav><button className="journal-link" id="journal-link">Bitácora <span>↗</span></button></header>
<main>
<section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star">✳</span> UNA VIDA, MUCHAS HISTORIAS</p><h1>Tu próxima<br />gran historia<br />empieza <em>aquí.</em></h1><p className="hero-description">Para los que subrayan, doblan esquinas<br />y nunca salen con un solo libro.</p><a className="button dark" href="#catalogo">Encuentra tu próxima lectura <span>↗</span></a><div className="hero-foot"><span className="line"></span> Libros completos. Lectura libre.</div></div><div className="hero-art" aria-label="Selección editorial de libros"><div className="art-caption">EL ARTE DE PERDERSE<br />ENTRE PÁGINAS.</div><div className="orbit">UN LIBRO LO CAMBIA TODO ·</div><div className="hero-book back"><span>MIGUEL DE<br />CERVANTES</span><strong>Don Quijote</strong><div className="sun"></div><small>UN VIAJE HACIA UNO MISMO</small></div><div className="hero-book front"><span>BENITO PÉREZ GALDÓS</span><strong>Marianela</strong><div className="arch"><div></div></div><small>PALABRAS QUE ABREN PUERTAS</small></div><div className="art-bottom"><span>01 / 12</span><span>LA SELECCIÓN MARGEN ↗</span></div></div></section>
<div className="manifesto"><span>Menos ruido. Más páginas.</span><span>✳</span><span>Encuentra lo que te mueve.</span><span>✳</span><span>Lee a tu manera.</span><span>✳</span><span>Menos ruido. Más páginas.</span></div>
<section className="catalog section" id="catalogo"><div className="section-heading"><div><p className="eyebrow">EL SIGUIENTE CAPÍTULO</p><h2>Una estantería de posibilidades<span>.</span></h2></div><span className="small-note">Elegidos con criterio,<br />para leer sin prisa.</span></div><div className="catalog-tools"><div className="tabs" role="group" aria-label="Filtrar por género"><button className="selected" data-filter="Todos">Todos</button><button data-filter="Narrativa">Narrativa</button><button data-filter="Poesía">Poesía</button><button data-filter="Clásicos">Clásicos</button><button data-filter="Cuentos">Cuentos</button><button data-filter="Teatro">Teatro</button></div><label className="search"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Un título, un autor, una idea…" aria-label="Buscar libros" /><kbd>/</kbd></label></div><div className="results-line"><p id="results-count">12 libros para abrir y leer</p><div id="sort-control"></div></div><div className="book-grid" id="book-grid"></div><p id="empty" className="empty" hidden>No encontramos esa historia. Prueba con otro título o autor.</p></section>
<section className="mood section" id="colecciones"><div className="mood-heading"><p className="eyebrow">NO SIEMPRE SABES QUÉ LEER. SÍ CÓMO TE SIENTES.</p><h2>Un libro para<br />este momento.</h2><p>Déjate llevar por el ánimo.<br />Nosotros ponemos las historias.</p></div><div className="mood-options"><button data-mood="calma"><span>01</span><strong>Necesito una pausa</strong><i>Respira. El mundo puede esperar.</i><b>↗</b></button><button data-mood="viaje"><span>02</span><strong>Quiero irme lejos</strong><i>Otros lugares. Otras vidas.</i><b>↗</b></button><button data-mood="ideas"><span>03</span><strong>Quiero otra perspectiva</strong><i>Ideas que abren ventanas.</i><b>↗</b></button></div></section>
<section className="reading-note section"><span className="quote-mark">“</span><blockquote>Hay historias que terminan.<br />Y otras que empiezan en ti.</blockquote><div><span>UNA NOTA DE MARGEN</span><p>Un pequeño recordatorio para<br />tu próximo capítulo.</p><button id="random-book" className="text-button">Sorpréndeme con un libro ↗</button></div></section>
<section className="journal-banner section"><div><p className="eyebrow">LO QUE LEES TAMBIÉN TE ESCRIBE</p><h2>Que una buena idea<br />no se quede entre páginas.</h2><p>Guarda citas, pensamientos y pequeños descubrimientos<br />en tu bitácora de lectura.</p></div><button className="button dark" id="journal-cta">Abrir mi bitácora <span>↗</span></button><span className="banner-star" aria-hidden="true">✳</span></section>
</main><footer><a className="brand" href="#">margen<span className="brand-dot">.</span></a><p>Historias que se quedan contigo.</p><span>Hecho para leer, sin prisa. © <span id="year"></span></span><a href="#catalogo">Volver a explorar ↑</a></footer>
<dialog id="book-dialog" aria-label="Detalle del libro"><button className="close" aria-label="Cerrar">×</button><div id="book-detail"></div></dialog>
<dialog id="shelf-dialog" aria-label="Mi biblioteca"><button className="close" aria-label="Cerrar">×</button><p className="eyebrow">TU UNIVERSO EN PAPEL</p><h2>Mi biblioteca<span>.</span></h2><p className="dialog-intro">Un lugar para las historias que quieres vivir.</p><div id="shelf-content"></div><button id="export" className="text-button">Descargar mi biblioteca PDF ↓</button></dialog>
<dialog id="journal-dialog" aria-label="Bitácora de lectura"><button className="close" aria-label="Cerrar">×</button><p className="eyebrow">PALABRAS QUE SE QUEDAN</p><h2>Tu bitácora<span>.</span></h2><p className="dialog-intro">Tus notas se guardan en este navegador.</p><form id="note-form"><label htmlFor="note-book">Libro o título de la nota</label><input id="note-book" required maxLength="120" placeholder="¿Qué estás leyendo?" /><label htmlFor="note-text">Tu descubrimiento</label><textarea id="note-text" required maxLength="3000" placeholder="Una cita, una idea, algo que no quieres olvidar…" rows="4"></textarea><button className="button dark" type="submit">Guardar nota ↗</button></form><div id="notes"></div></dialog>
<div id="reader-root"></div><div className="toast" role="status" id="toast"></div>
</>}
