import assert from 'node:assert/strict';
import {flipPoint,migratePosition,readingStatus} from '../reader-model.js';
const bounds={left:75,top:18,pageWidth:350,width:700,height:510};
assert.deepEqual(flipPoint(bounds,'landscape',-1),{x:85,y:526});
assert.deepEqual(flipPoint(bounds,'portrait',-1),{x:435,y:526});
assert.deepEqual(flipPoint(bounds,'landscape',1),{x:765,y:526});
assert.equal(migratePosition({paragraphs:[],pages:[{blocks:[]}]},0),0);
const words=Array.from({length:500},(_,i)=>`word${i}`).join(' ');
const oldFirst=words.slice(0,words.lastIndexOf(' ',750));
const next=words.substring(oldFirst.length+1);
const data={paragraphs:[words],pages:[{blocks:[]},{blocks:[{text:words}]}]};
assert.equal(migratePosition(data,1),1);
console.log('Bidirectional flip coordinates and migration checks passed');
assert.equal(readingStatus(null).label,'Por leer');
assert.equal(readingStatus({page:0,total:403}).percent,0);
assert.equal(readingStatus({page:20,total:403,contentEnd:380}).label,'Leyendo');
assert.equal(readingStatus({page:378,furthestPage:379,contentEnd:380,total:403}).label,'Leído');
assert.equal(readingStatus({page:5,furthestPage:379,completed:true,contentEnd:380,total:403}).percent,100);
console.log('Automatic reading states and completion persistence passed');
